server:
    port: 9999

spring:
    # redis配置信息
    redis:
        host: localhost
        port: 6379
        database: 1
    # mysql配置信息
    datasource:
        url: jdbc:mysql://localhost:3306/bigdatasc
        username: root
        password: 180229gxk.
    # hbase配置信息
    data:
        hbase:
            quorum: "node1:2181,node2:2181,node3:2181"
            rootDir: hdfs://node1:9000/hbase
            nodeParent: /hbase

mybatis:
    mapper-locations: /mapper/*.xml
    type-aliases-package: com.guet.courseselecthelper.demos.entity
    configuration:
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl